[package]
edition = "2021"
name = "syn_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "syn_integrity"

[dependencies]
hc_zome_syn_integrity = {git = "https://github.com/holochain/syn", branch = "for-hdk-v0.4.0-dev"}
